#pragma once

//#include "stdafx.h"

int mainC_examples();
int mainTest();
int mainComplexInheritance();
int mainExceptions();
int mainException();
int mainFriendInheritance();
int mainFunctionObject();
int mainNewDelete();
int mainRational();
int mainSimpleInheritance();
int mainJoin();
int mainVector();
int mainTuple();
int mainTemplateFunction();
int mainTemplateClass();
int mainString();
int mainStack();
int mainSet();
int mainSet14();
int mainQueue();
int mainNullptr();
int mainMap();
int mainList();
int mainLambda();
int mainIterator();
int mainIostreamFormatting();
int mainIostreamFile();
int mainDeque();
int mainFor();
int mainAuto();
int mainAlgorithm();
int mainStack();
int mainRandy();
int fileIo();
int MemFrag();
int nondupset();
int threadlightly();
int mainSort();